### ISSUE TITLE
Couldn't Install Tailwind CSS

### ISSUE THREAD

**Issue by teoh4770** [LaurierCS/CodingJourney#10]
I have downloaded the node.js package, and run the following code :
**pipenv install** to install all the new packages needed.
But I get error message...
![Screenshot 2022-04-12 at 2 55 28 PM](https://user-images.githubusercontent.com/98545971/163033589-76d64f30-5e26-4bd7-9050-a82cb8c0a195.png)
This is one of the part of the error i get.

**Comment by juancwu** [comment]
I reproduce the error but haven't been able to find a solution for it.

**Comment by juancwu** [comment]
This issue should be resolved with this PR https://github.com/LaurierCS/Pod4/pull/11
