### ISSUE TITLE
couldn't create a new style in tailwind.src.css file

### ISSUE THREAD

**Issue by teoh4770** [LaurierCS/CodingJourney#47]
I try to create the styling for the message that appear every time the user save the form, since like different type of message should have different type of color indicate the meaning of it.
Each type of messages has its own class, can refer to this screenshot: 

![Screenshot 2022-05-15 at 12 37 19 AM](https://user-images.githubusercontent.com/98545971/168457503-aaffcdb5-46a4-443b-bafb-10e8f3ce84c2.png)

the class generate by the warning message, would be 'warning',
the class generate by the success message, would be 'success'

so I just create the new classes styling in the tailwind source css file, in the utility part(not sure if I correct), but tailwind would not generate the styling for me...

**Comment by juancwu** [comment]
Tailwind would not generated them because there are not used anywhere in any of the existing templates. So what tailwind does is that it scans our html files and add the classes that are used only. If you want to styled them you could add a class at the bottom of the `tailwind.src.css` file that would be included in the generated `tailwind.css` file.

**Comment by teoh4770** [comment]
thanks I will try that next time

**Comment by juancwu** [comment]
@CheeKianTeoh Were you able to solve the problem?

**Comment by teoh4770** [comment]
![Screenshot 2022-05-17 at 1 58 34 PM](https://user-images.githubusercontent.com/98545971/168879357-7dddc1e8-aced-44d9-83ec-131696be0668.png)
<img width="759" alt="Screenshot 2022-05-17 at 1 59 03 PM" src="https://user-images.githubusercontent.com/98545971/168879517-c28956d2-885e-4463-9be3-1fe7c3078c77.png">

It didn't :< I'm not sure if i didn't something wrong here?
